name: Feature Request for Parent Tweet
description: Would it be possible to implement a way to get the content of a parent tweet in which an account is mentioned? Example: @UserA tweets "hello world". @UserB mentions @UserC in a reply. Retrieve the contents of @userA's tweet. 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        ## Self Check
        - Try searching existing GitHub Issues (open or closed) for similar issues.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Would it be possible to implement a way to get the content of a parent tweet in which an account is mentioned? Example: @UserA tweets "hello world". @UserB mentions @UserC in a reply. Retrieve the contents of @userA's tweet. 'enhancement'
      description: A clear description of what the feature is.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Would this fix a problem you're experiencing? If so, specify.
  - type: textarea
    attributes:
      label: Did you consider other alternatives?
      description: If so, specify
  - type: input
    attributes:
      label: Additional context
